const langArrEN = {
    "explain-text" : "Drone Management Software - Elevate Your Flying Experience",
    "lang-download-button": "Latest Asv.Drones version",
    "lang-download-button-text": "Download latest version now by the link",
    "theme_label": "Theme",
    "lang-system-req-label": "Minimal system requirements:",
    "lang-cpu-label": "Processor (CPU): Dual-core processor, 1.5 GHz or equivalent",
    "lang-gpu-label":"Graphics: Integrated graphics with OpenGL 3.3 support",
    "lang-ram-label":"Memory (RAM): 4 GB",
    "lang-hdd-label":"Storage: 20 GB of available space",
    "lang-internet-label":"Network: Broadband internet connection for software updates and communication with drones",
    "lang-setup-install-label": "Installation and Setup",
    "lang-support-device": "Supported devices",
    "lang-support-os": "Suppotred OS",
    "lang-drone-control": "Drone Control",
    "lang-drone-control-manual": "Manual Control",
    "lang-drone-control-automatic": "Automatic Control",
    "lang-drone-control-manual-desc": "Asv.Drones offers users the capability to take direct control of drones through manual control mode. This feature provides users with hands-on control over drone movement, allowing for precise maneuvers and real-time adjustments.",
    "lang-drone-control-automatic-desc": "Automatic flight modes, enabling automated and pre-planned missions for drones. These modes provide users with the ability to define waypoints, actions, and specific flight paths, enhancing the efficiency and precision of drone operations.",
    "lang-read-more":"Read more",
    "lang-read-more-1":"Read more",
    "lang-read-more-2":"Read more",
    "lang-check-out": "Check Out",
    "lang-want-more": "Want more?",
    "lang-about-docs": "Documentation is full describe of features and specifics of Asv.Drones",
    "lang-drone-connect-text":"Step by step guide about drone connect",
    "lang-drone-connect": "Drone connect instructions"
    
}